steps:
  - label: "CUDA support"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    command: |
      julia -e 'using Pkg;

                println("--- :julia: Instantiating project");
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.develop(PackageSpec(path=joinpath(pwd(), "lib/FluxCUDA")));

                println("+++ :julia: Running tests");
                Pkg.test("FluxCUDA"; coverage=true);'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  - label: "AMD support"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    command: |
      julia -e 'using Pkg;

                println("--- :julia: Instantiating project");
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.develop(PackageSpec(path=joinpath(pwd(), "lib/FluxAMDGPU")));

                println("+++ :julia: Running tests");
                Pkg.test("FluxAMDGPU"; coverage=true);'
    soft_fail:
      - exit_status: 1
    agents:
      queue: "juliagpu"
      rocm: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
