steps:
  - label: "GPU integration"
    plugins:
      - JuliaCI/julia#v1:
          version: '1.5'
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
