steps:
  - label: "CUDA support"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    command: |
      julia -e 'using Pkg;

                println("--- :julia: Instantiating project");
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.add(PackageSpec(url="https://github.com/FluxML/FluxCUDA.jl", rev="main"));
                Pkg.instantiate();

                println("+++ :julia: Running tests");
                Pkg.test("FluxCUDA"; coverage=true);'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
